import Head from "next/head";
import Footer from "../componentes/footer";
import Header from "../componentes/header";
import { getSession } from "next-auth/react";
import { useRouter } from "next/router";
import Link from "next/link";
import axios from "axios";
import Paginado from "componentes/paginado";
import Buscador from "componentes/buscador";

export default function Homex(props) {
  const router = useRouter();
  if (props.context.r) {
    var cat = props.context.r;
  }
  if (props.context.q) {
    var cat = props.context.q;
  }

  return (
    <div className="contenedor">
      <Head>
        <title>Inicio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="app">
        <Header perfil={props.session ? props.session.user : ""} />
        <main className="main">
          <ul className="listado-inicio">
            <li className="titulo-home">
              <h1>Administra tus Grupos.</h1>
            </li>
            <li className="li-buscador">
              <Buscador s={props.context.s} admin={true}/>
            </li>
            {props.posts.docs != '' ? props.posts.docs.map((post) => (
              <li className="inicio-li" key={post._id}>
                <Link href={`/${post._id}`}>
                  <a>
                    <div className="contenedor-texto">
                      <div className="titulo-del-grupo">{post.titulo}</div>{" "}
                      <div className="categoria-red">
                        {post.categoria} - {post.red}
                      </div>
                    </div>
                  </a>
                </Link>
              </li>
            )): 'No se encontro ningun Grupo que administres o coinsida con tu busqueda'}
          </ul>

          <Paginado
            page={props.posts.page}
            prevPage={props.posts.prevPage}
            nextPage={props.posts.nextPage}
            cat={cat}
            q={props.context.q}
            r={props.context.r}
            s={props.context.s}
            admin={true}
          />

          <div className="text-informacion-footer">
            <p>
              Aquí encontrarás muchos enlaces de canales o grupos de diferentes
              redes sociales activos para apuntarte. Este sitio también te ayuda
              a añadir tus grupos de tu red social favorita gratuitamente.
              Puedes unirte a un número ilimitado de grupos de la red social que
              quieras a través de este sitio web. Y si no encuentras tu grupo
              preferido... ¡Créalo!. De esa manera, muchas personas encontrarán
              tu Grupo y se unirán.
            </p>
          </div>
        </main>
        <Footer />
      </div>
    </div>
  );
}

export const getServerSideProps = async (context) => {
  try {
    const session = await getSession(context);
    if (!session)
      return {
        redirect: {
          destination: "/",
          permanent: false,
        },
      };
    const { data } = await axios.get(
      `${process.env.PAGE_URL}/api/grupos/listado`,
      {
        params: {
          creador: session.user.email,
          s: context.query.s,
          q: context.query.q,
          r: context.query.r,
          pag: context.query.pag,
        },
      }
    );
    return {
      props: {
        posts: data,
        session,
        context: context.query,
      },
    };
  } catch (error) {
    return {
      notFound: true,
    };
  }
};