import Head from "next/head";
import Footer from "../componentes/footer";
import Header from "../componentes/header";
import { getSession } from "next-auth/react";
import Link from "next/link";
import axios from "axios";
import Paginado from "componentes/paginado";
import { useState } from "react";
import Buscador from "componentes/buscador";

export default function Homex(props) {
  console.log(props.context);
  if (props.context.r) {
    var cat = props.context.r;
  }
  if (props.context.q) {
    var cat = props.context.q;
  }

  return (
    <div className="contenedor">
      <Head>
        <title>Inicio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="app">
        <Header perfil={props.session ? props.session.user : ""} />
        <main className="main">
          <ul className="listado-inicio">
            <li className="li-buscador">
              <Buscador s={props.context.s}/>
            </li>
            <li className="titulo-home">
              {props.context.r ? <h1>Grupos de {props.context.r}</h1> : ""}
              {props.context.q ? <h1>Grupos de {props.context.q}</h1> : ""}
              {!props.context.q && !props.context.r ? (
                <h1>Únete a Grupos de redes Sociales.</h1>
              ) : (
                ""
              )}
            </li>
            {props.posts.docs != ""
              ? props.posts.docs.map((post) => (
                  <li className="inicio-li" key={post._id}>
                    <Link href={`/${post._id}`}>
                      <a>
                        <div className="contenedor-texto">
                          <div className="titulo-del-grupo">{post.titulo}</div>
                          <div className="categoria-red">
                            {post.categoria} - {post.red}
                          </div>
                        </div>
                      </a>
                    </Link>
                  </li>
                ))
              : (<div className="no-hay-resultados">
                <h2>Upssss.</h2>
                <p>Parece que lo que esta intentando buscar no se encuentra o no lo busco correctamente</p>
                <p>Intenta buscar otra cosa o haga click en alguna de las categorias a continuacion.</p>
                <ul className="categorias-links">
                  <li><Link href='/?r=Telegram'><a>Telegram</a></Link></li>
                  <li><Link href='/?r=Whatsapp'><a>Whatsapp</a></Link></li>
                  <li><Link href='/?r=Facebook'><a>Facebook</a></Link></li>
                  <li><Link href='/?r=Reddit'><a>Reddit</a></Link></li>
                  <li><Link href='/?r=Discord'><a>Discord</a></Link></li>
                  <li><Link href='/?r=Signal'><a>Signal</a></Link></li>
                  <li><Link href='/?r=Viber'><a>Viber</a></Link></li>
                </ul>
                <ul className="categorias-links">
                  <li><Link href='/?q=Amistad'><a>Amistad</a></Link></li>
                  <li><Link href='/?q=Arte'><a>Arte</a></Link></li>
                  <li><Link href='/?q=Apuestas'><a>Apuestas</a></Link></li>
                  <li><Link href='/?q=Ayuda'><a>Ayuda</a></Link></li>
                  <li><Link href='/?q=Ciencia'><a>Ciencia</a></Link></li>
                  <li><Link href='/?q=Debates'><a>Debates</a></Link></li>
                  <li><Link href='/?q=Deportes'><a>Deportes</a></Link></li>
                  <li><Link href='/?q=Fans'><a>Fans</a></Link></li>
                  <li><Link href='/?q=Frikis'><a>Frikis</a></Link></li>
                  <li><Link href='/?q=Futbol'><a>Futbol</a></Link></li>
                  <li><Link href='/?q=Gamers'><a>Gamers</a></Link></li>
                  <li><Link href='/?q=Lectores'><a>Lectores</a></Link></li>
                  <li><Link href='/?q=Marketing'><a>Marketing</a></Link></li>
                  <li><Link href='/?q=Musica'><a>Musica</a></Link></li>
                  <li><Link href='/?q=Politica'><a>Politica</a></Link></li>
                  <li><Link href='/?q=Risas'><a>Risas</a></Link></li>
                  <li><Link href='/?q=Trading'><a>Trading</a></Link></li>
                  <li><Link href='/?q=Musica'><a>Musica</a></Link></li>
                  <li><Link href='/?q=Series'><a>Series</a></Link></li>
                  <li><Link href='/?q=Viajar'><a>Viajar</a></Link></li>
                  <li><Link href='/?q=Adultos'><a>Adultos</a></Link></li>
                </ul>
              </div>)}
          </ul>

          <Paginado
            page={props.posts.page}
            prevPage={props.posts.prevPage}
            nextPage={props.posts.nextPage}
            cat={cat}
            q={props.context.q}
            r={props.context.r}
            s={props.context.s}
          />

          <div className="text-informacion-footer">
            {cat ? (
              <p>
                Aquí encontrarás muchos enlaces de canales o grupos de {cat}{" "}
                activos para apuntarte. Este sitio también te ayuda a añadir tus
                grupos de {cat} gratuitamente. Puedes unirte a un número
                ilimitado de grupos de {cat} a través de este sitio web. Y si no
                encuentras tu grupo preferido... ¡Créalo!. De esa manera, muchas
                personas encontrarán tu Grupo de {cat}.
              </p>
            ) : (
              <p>
                Aquí encontrarás muchos enlaces de canales o grupos de{" "}
                diferentes redes sociales activos para apuntarte. Este sitio
                también te ayuda a añadir tus grupos de tu red social favorita
                gratuitamente. Puedes unirte a un número ilimitado de grupos de
                la red social que quieras a través de este sitio web. Y si no
                encuentras tu grupo preferido... ¡Créalo!. De esa manera, muchas
                personas encontrarán tu Grupo y se unirán.
              </p>
            )}
          </div>
        </main>
        <Footer />
      </div>
    </div>
  );
}

export const getServerSideProps = async (context) => {
  try {
    const session = await getSession(context);
    const { data } = await axios.get(
      `${process.env.PAGE_URL}/api/grupos/listado`,
      {
        params: {
          s: context.query.s,
          q: context.query.q,
          r: context.query.r,
          pag: context.query.pag,
        },
      }
    );
    return {
      props: {
        posts: data,
        session,
        context: context.query,
      },
    };
  } catch (error) {
    return {
      notFound: true,
    };
  }
};
