import Footer from "componentes/footer";
import Header from "componentes/header";
import { signIn, getSession } from "next-auth/react";
import Head from "next/head";
import Image from "next/image";
const Login = () => {
  return (
    <div className="loginPage">
      <Head>
        <title>Login rglottery</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <div className="login-page app">
        <Header />
        <main className="main">
          <div className="card-login">
            <h2 className="h2-login">Inicia Sesión con tu Cuenta de Google.</h2>
            <button
              className="btn-login-google"
              onClick={() => signIn("google")}
            >
              Iniciar sesion con <div className="espacio-ante-google"></div>
              <Image src='/google.png' className="img-logo-google" width={72} height={25} alt='Google'/>
            </button>
            <h2 className="h2-login">¿Porque iniciar Sesión?</h2>
            <p className="p-login">
              Al iniciar sesión puedes publicar tus Grupos de Redes Sociales en
              este sitio web siempre que quieras, sin limitaciones, también
              puedes editar o eliminar los Grupos que publiques, cuando quieras.
            </p>
            <h2 className="h2-login">¿Es necesario Iniciar Sesión?</h2>
            <p className="p-login">
              Si tu intención no es publicar tus Grupos y solo quieres acceder a
              los grupos para participar en ellos, no es necesario que Inicies
              Sesión, todos los enlaces de los grupos publicados aquí están
              disponibles de manera pública para que te unas cuando quieras.
            </p>
          </div>
        </main>
        <Footer />
      </div>
    </div>
  );
};
export default Login;

export const getServerSideProps = async (context) => {
  const session = await getSession(context);

  if (session)
    return {
      redirect: {
        destination: "/admin",
        permanent: false,
      },
    };
  return {
    props: {},
  };
};
