import { signIn, getSession } from "next-auth/react"
import Head from "next/head"
const Login = () => {
  return(
    <div className="loginPage">
    <Head>
      <title>Login rglottery</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <div className="login-page">
      <button onClick={() => signIn('google')}>
        Iniciar sesion con Google
      </button>
    </div>

  </div>
    
  )
}
export default Login

export const getServerSideProps = async(context) => {

  const session = await getSession(context)
  
  if(session) return {
    redirect: {
      destination: '/admin',
      permanent: false
    }
  }
    return{
      props: {}
    }
  };